name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      # 3. Kiểm tra môi trường
      - name: Flutter doctor
        run: flutter doctor

      # 4. Cài dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build APK (PRO MAX)
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # 6. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/*.apk